### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by vincentbernat** [ansible-collections/ansible.netcommon#123]
##### SUMMARY
There is no documentation on how to run tests locally. I have tried:

- `tox -e venv pytest` (problem with paths)
- `ansible-test units --tox` (not a recognized argument)
- `ansible-test units` (cannot use the venv)
- `tox -e venv ansible-test units` (complain about `HOME` missing)

The documentation from Ansible does not seem to cover out-of-tree modules.

##### ISSUE TYPE
- Documentation Report

**Comment by GomathiselviS** [comment]
Hello @vincentbernat 

Please refer to this [link](https://docs.ansible.com/ansible/latest/dev_guide/testing_units.html#testing-units) for unit test related commands. @samccann  should be able to provide more information.

**Comment by vincentbernat** [comment]
This guide doesn't work for out of trees module. Notably, `ansible-test units --tox` error out saying `--tox` is not recognized:

```
usage: ansible-test [-h] COMMAND ...
ansible-test: error: unrecognized arguments: --tox
```

The best I am able to do is manually enter the venv created by tox and then use `ansible-test` from here. However, for some reason, it tries to use all the wrong Python interpreters (I have 3.8 installed on my system):

```
WARNING: Skipping unit tests on Python 2.6 due to missing interpreter.
WARNING: Skipping unit tests on Python 3.5 due to missing interpreter.
WARNING: Skipping unit tests on Python 3.6 due to missing interpreter.
WARNING: Skipping unit tests on Python 3.7 due to missing interpreter.
WARNING: PyYAML is not installed for interpreter: /usr/bin/python2.7
Unit test with Python 2.7
/tmp/python-a0j2tp9_-ansible/python: No module named pytest
ERROR: Command "pytest --boxed -r a -n auto --color yes -p no:cacheprovider -c /home/bernat/code/blade/ansible_collections/ansible/netcommon/.tox/venv/lib/python3.8/site-packages/ansible_test/_data/pytest.ini --junit-xml /home/bernat/code/blade/ansible_collections/ansible/netcommon/tests/output/junit/python2.7-units.xml --strict-markers tests/unit/module_utils/network/common/test_config.py tests/unit/module_utils/network/common/test_parsing.py tests/unit/module_utils/network/common/test_utils.py tests/unit/modules/network/cli/test_cli_config.py tests/unit/plugins/connection/test_libssh.py tests/unit/plugins/connection/test_netconf.py tests/unit/plugins/connection/test_network_cli.py tests/unit/plugins/filter/test_ipaddr.py tests/unit/plugins/filter/test_network.py" returned exit status 1.
```

**Comment by felixfontein** [comment]
Check out https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#testing-collections, it describes testing in the collection world. Best to simply run `ansible-test units --docker -v`, or for example `ansible-test units --docker -v --python 3.5` to restrict to Python 3.5.

**Comment by gundalow** [comment]
Hi,
This is a good point, we do need some basic common how to get started with testing

Assuming you have Python 3.7 installed
```
mkdir -p ansible_collections/ansible
cd ansible_collections/ansible
git clone https://github.com/ansible-collections/ansible.netcommon netcommon
cd netcommon
ansible-test units --venv --python 3.7
```

**Comment by vincentbernat** [comment]
Thanks to you both. Both your methods work fine for me!

**Comment by Qalthos** [comment]
I'm going to take that as this issue is solved.
