### ISSUE TITLE
merge cloud.common in ansible.netcommon?

### ISSUE THREAD

**Issue by goneri** [ansible-collections/ansible.netcommon#129]
The new `vmware.vmware_rest` collection relies on a component called `ansible_module-turbo` (https://github.com/goneri/ansible_module-turbo).  
This shared library gives the ability to start a cache to speed up the module execution. The new `cloud.common` embeds this piece of code (https://github.com/ansible-collections/cloud.common). This is very useful for cases where the module execution is slowed down by large Python dependencies, or a slow session opening.
The feature may ultimately be merged in ansible/ansible, but for now we need to ship it through a collection.

I've started a new collection because this is rather specific to the cloud collections. But I may be wrong, and I don't want to create and maintain a myriad of new collections. Do you think it would make sense to merge the two collections, ideally before `vmware_vmware_rest` get released?

**Comment by Qalthos** [comment]
Is the only thing in this collection the `turbo/` module_utils dir, or is there something else that I'm missing? I have no problems with that getting added to netcommon... but it might be more productive to have a conversation about this over a concrete PR making the move

**Comment by goneri** [comment]
Thanks for the answer @Qalthos. I close this for now since the cloud.common collection has been published and I feel like it's to late to change that before vmware.vmware_rest 1.0.0 release.
