### ISSUE TITLE
Enable netconf test in CI for nxos

### ISSUE THREAD

**Issue by ganeshrn** [ansible-collections/ansible.netcommon#200]
##### SUMMARY

With reference to PR https://github.com/ansible-collections/ansible.netcommon/pull/185
This issue is raised to track enabling of netconf jobs for nxos when the nxos image is upgraded in zuul CI.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by NilashishC** [comment]
The current NX-OSv in our CI doesn't support netconf. We should be able to do this once it is upgraded to NX-OS 9.3.6.

cc @pabelanger @GomathiselviS
