### ISSUE TITLE
Network modules should work in linux

### ISSUE THREAD

**Issue by holmesb** [ansible-collections/ansible.netcommon#300]
##### SUMMARY
The net_* modules should also work in ubuntu & rhel-based distros, not just on specialist [network hardware\OSs](https://docs.ansible.com/ansible/latest/network/user_guide/platform_index.html#settings-by-platform).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
net_* modules

##### ADDITIONAL INFORMATION
```yaml (paste below)
- name: create VRF named MANAGEMENT
  net_vrf:
    name: MANAGEMENT
    state: present
```

on Ubuntu results in:
```
TASK [kubespray_wrapper : vrf - create VRF named MANAGEMENT] ************************************************************************************************************************************************************************

Thursday 01 July 2021  12:24:34 +0100 (0:00:00.352)       0:00:06.079 *********
fatal: [server01]: FAILED! => {"msg": "ansible_network_os must be specified on this host to use platform agnostic modules"}
```

**Comment by Qalthos** [comment]
The `net_*` modules are also deprecated, and no additional functionality is likely at the moment.

Additionally, for context on what sort of an undertaking this would be, the `net_*` modules do not do anything by themselves. They take the contents of the `network_os` and redirect the parameters to a module named `$(network_os)_$(resource)`, if it can find one. So in order for the `net_vrf` module to support an arbitrary linux host, a `linux_vrf` module would need to be created that matches the parameters of the `net_vrf` module.

This is not an insurmountable bar to clear, but again, these modules are deprecated and will be removed soon, and most `net_*` modules other than `net_vrf` have had all the implementing modules (`ios_vlan`, for example) deprecated with the shift to resource modules which have a much different argspec and module flow. And while this has not yet happened to vrf, for example, we intend to replace all of these modules in time.
