### ISSUE TITLE
Usability netconf_config

### ISSUE THREAD

**Issue by geordish** [ansible-collections/ansible.netcommon#36]
I was recently using the netconf_config module, and spent a few hours diagnosing an issue with a simple payload. 

The upshot was I was not enclosing my payload in `<config>...</config>`. This was giving me the following helpful error message.

``` 
"msg": "Element [{http://cisco.com/ns/yang/Cisco-IOS-XR-shellutil-cfg}host-names] does not meet requirement"
```

Can I suggest that some better error handling is implemented to give a useful error message as to why the payload is not correct, and updating the documentation to make it clear that this is a requirement.

```
dave-bell-mac:prototype-ansible dave.bell$ ansible --version
ansible 2.9.9
  config file = /Users/dave.bell/git/prototype-ansible/ansible.cfg
  configured module search path = ['/Users/dave.bell/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dave.bell/Library/Python/3.7/lib/python/site-packages/ansible
  executable location = /Users/dave.bell/Library/Python/3.7/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]
```

(FYI, I think there is supposed to be a template of information required for an issue, but that is missing...)

**Comment by ganeshrn** [comment]
@geordish Can you please check if PR https://github.com/ansible-collections/ansible.netcommon/pull/66 fixes the issue

**Comment by geordish** [comment]
Hi @ganeshrn looks good to me!

Thanks
