### ISSUE TITLE
Sanity tests failing in ansible.netcommon

### ISSUE THREAD

**Issue by dmsimard** [ansible-collections/ansible.netcommon#417]
##### SUMMARY
We are running sanity tests across every collection included in the Ansible community package (as part of [this issue](https://github.com/ansible-community/community-topics/issues/96)) and found that ``ansible-test sanity --docker`` against ansible.netcommon 3.0.0 fails with ansible-core 2.13.0rc1 in ansible 6.0.0a2.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
n/a

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.0rc1]
```

##### COLLECTION VERSION

```paste below
3.0.0
```

##### STEPS TO REPRODUCE

```yaml
ansible-test sanity --docker
```

##### EXPECTED RESULTS

Tests are either passing or ignored.

##### ACTUAL RESULTS

```paste below
ERROR: Found 1 import issue(s) on python 3.10 which need to be resolved:
ERROR: plugins/connection/netconf.py:161:0: traceback: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
ERROR: The 1 sanity test(s) listed below (out of 43) failed. See error output above for details.
import --python 3.10
ERROR: Command "podman exec ansible-test-controller-iFWczulb /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/root/ansible_collections/ansible/netcommon LC_ALL=en_US.UTF-8 /usr/bin/python3.10 /root/ansible/bin/ansible-test sanity --containers '{}' --skip-test pylint --metadata tests/output/.tmp/metadata-97vumbuh.json --truncate 0 --color no --host-path tests/output/.tmp/host-alfuhwzs" returned exit status 1.
```

**Comment by Qalthos** [comment]
That should already be fixed with https://github.com/ansible-collections/ansible.netcommon/pull/412, which will be in the next release, but thanks for the heads up!
