### ISSUE TITLE
git tags' naming convention with "v" in release 5.1.2

### ISSUE THREAD

**Issue by shk3bq4d** [ansible-collections/ansible.netcommon#562]
Hello,

release 5.1.2's git tag is v5.1.2, while past releases don't have the `v` in their tag name.

Is this intended and the new normal or a mistake?

Thank you and best regards,

cc: @Qalthos

**Comment by KB-perByte** [comment]
Hey @shk3bq4d it is an intended change, The Galaxy/ Ah releases are going to follow Semantic Versioning but the networking collections are to follow releases with v prefixes. 
Regards.
