### ISSUE TITLE
Missing documentation for ipaddr functions

### ISSUE THREAD

**Issue by ryanmerolle** [ansible-collections/ansible.netcommon#58]
##### SUMMARY

It looks like there are several functions in the ipaddr filter function that are just not documented.  One such example is cidr_lookup.  It seems like it is intended to take an ipaddr var and check if it is in the subnet  list provided.  

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
ipaddr.py

##### ANSIBLE VERSION

```
ansible 2.9.9
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
```

**Comment by Qalthos** [comment]
cc @samccann

**Comment by Qalthos** [comment]
I think this is largely solved in the ansible.utils collection. If not, reopen on that collection where the content now lives
