### ISSUE TITLE
ansible-lint CI dependency is broken

### ISSUE THREAD

**Issue by wrouesnel** [ansible-collections/ansible.netcommon#594]
When submitting PRs to this repository, they are all failing because the ansible-lint CI dependency is broken and unable to find the requirements file it's configured to download.

Example: https://github.com/ansible-collections/ansible.netcommon/actions/runs/6636142238/job/18028142705?pr=593

(template removed since this isn't actually a problem with the product at all)

**Comment by KB-perByte** [comment]
@wrouesnel Thanks for reporting the issue. Please note that the failure of ansible-lint CI is noted and is being worked on. 
It should be fixed shortly. Sorry for the inconvenience.
Closing the issue, please feel free to tag me if you need any information regarding it.
Regards.
